### ISSUE TITLE
i have installed how to run it

### ISSUE THREAD

**Issue by sant527** [xtrinch/fcm-django-web-demo#1]
I have created a new python virtualenv and then copied the folder there.

then i did: pip install -r requirements.txt

It installed all the requirement files:

After that how to do

**Comment by xtrinch** [comment]
Perhaps try running the server with `python -m SimpleHTTPServer`?

**Comment by sant527** [comment]
python -m http.server 8080
SimpleHTTPServer i s deprecated

**Comment by xtrinch** [comment]
That is just a warning. I have now added a better readme, it should explain how to use it in more detail. Let me know if you have any more issues.
