### ISSUE TITLE
fcm-django-web-demo update requirement file packages version

### ISSUE THREAD

**Issue by harem234** [xtrinch/fcm-django-web-demo#10]
the requirement right now install django 3.0.7
and django-cors-headers==2.1.0  , needs to import 'six' package from django __init__.py.

and as we know it is not available in django 3

**Comment by xtrinch** [comment]
I've updated django-cors-headers requirements, and removed the python 2 mentions in the readme.
That should fix the six issue as django-cors-headers==3.3.0 is django 3 compatible

**Comment by xtrinch** [comment]
Feel free to re-open if any more issues pop up!
