### ISSUE TITLE
How to integrate django templates

### ISSUE THREAD

**Issue by saileshkush95** [xtrinch/fcm-django-web-demo#12]
Thanks for this demo and for your amazing works, this demo is working properly. But still I've some questions.
firebase-messaging-sw.js is not included in index.html so what is the use case of this file. How this file is integrated in this project. 

Does this project work with pure django templates? If this works, how can i integrate this project with django templates.

can you please, create one new branch django tempate demo. This will help for beginners like me

**Comment by xtrinch** [comment]
Sorry, I don't currently have time to create a new demo project with django templates.

Yes, you should be able to use it with server side rendering, probably even easier. Instead of going through the API's, you should be able to call fcm-django's functions directly.
