### ISSUE TITLE
django-sslserver out of date

### ISSUE THREAD

**Issue by SirWumpus** [xtrinch/fcm-django-web-demo#18]
Trying to start the SSL example fails because `django.utils._os.upath` and friends no longer available.  A simple update of the module to head (0.22) resolved the issue.

**Comment by xtrinch** [comment]
Which module did you update to 0.22?

**Comment by SirWumpus** [comment]
Module `django-sslserver`.

**Comment by xtrinch** [comment]
Thanks. Resolved in latest master
