### ISSUE TITLE
Support for FCM HTTP v1?

### ISSUE THREAD

**Issue by SirWumpus** [xtrinch/fcm-django-web-demo#20]
It appears the `fcm-django-web-demo` (and assume also `fcm-django`) uses the legacy HTTP API.   Will there be support for the FCM HTTP v1 protocol?  [Migration notes](https://firebase.google.com/docs/cloud-messaging/migrate-v1).

**Comment by xtrinch** [comment]
Yes, the 1.0.0 version is using FCM HTTP v1 protocol.
