### ISSUE TITLE
TypeError: send_message() missing 1 required positional argument: 'message'

### ISSUE THREAD

**Issue by bartkim0426** [xtrinch/fcm-django-web-demo#25]
After following documentation, I got the error below

```
TypeError: send_message() missing 1 required positional argument: 'message'
```

After I checked the code, I found out that `message` argument is mandatory. (https://github.com/xtrinch/fcm-django/blob/bb239015f348c4b58fbd556adac2f11fd73c0e9f/fcm_django/models.py#L117)

So is it should be changed into below?

```
device.send_message(message=Message(notification=Notification(title='title', body='message')))
```

**Comment by onshadeep** [comment]
I am also getting the same issue. How can we solve it?

this is what I had tried
`devices.send_message(title=self.title, body=self.description, click_action=self.link)`

and the below error is coming on the production server
`TypeError: send_message() missing 1 required positional argument: 'message'`

**Comment by onshadeep** [comment]
@bartkim0426 How can we import Message? I used from fcm_django.messaging import Message, Notification but I am getting error is title invalid

**Comment by xtrinch** [comment]
`from firebase_admin.messaging import Message, Notification`

Also the docs have been updated and should now be correct.

**Comment by apsabareesh** [comment]
> `from firebase_admin.messaging import Message, Notification`
> 
> Also the docs have been updated and should now be correct.

Please update the example in readme as well.
