### ISSUE TITLE
`coreapi` must be installed for schema support.

### ISSUE THREAD

**Issue by muffer2** [xtrinch/fcm-django-web-demo#35]
<img width="682" alt="git_issue" src="https://github.com/xtrinch/fcm-django-web-demo/assets/45001844/08487ae4-0882-46b3-a039-52953b1a0d5b">

First, I tried installing requirements.txt but I was getting the same error, so I updated the modules, it was working fine for me about a week ago but since yesterday, I am facing this error

current versions that I'm using:-
coreapi==2.3.3
coreschema==0.0.4
Django==4.2.7
django-cors-headers==4.3.1
django-sslserver==0.22
djangorestframework==3.14.0
fcm-django==2.0.0
six==1.16.0
urllib3==2.1.0

**Comment by hdkhanh462** [comment]
i have same error:
"AssertionError: `coreapi` must be installed for schema support."

**Comment by xtrinch** [comment]
Can't reproduce. Feel free to reopen with more info (which python version, ...)
