### ISSUE TITLE
Does this example work out of the box?

### ISSUE THREAD

**Issue by Nneji123** [xtrinch/fcm-django-web-demo#36]
Does this example work out of the box or do I need to replace the credentials.json?

**Comment by xtrinch** [comment]
I've gotten an email recently that public keys will be disabled soon if they haven't been yet, so please use your own

**Comment by Nneji123** [comment]
Okay do I have to replace just the credentials.json or what else do I have to replace?

**Comment by xtrinch** [comment]
Correct, credentials.json

**Comment by Nneji123** [comment]
What do i replace this with? Is it my django server secret_key? or is it the vapid key gotten from firebase console?
   ```python
    FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "AAAAUBWqdfo:APA91bEm3ib6_TlLIJ5YpAU6BjyQ7X9GoXeghkgqiBwNPPkr_FP9NjdhVk8EZqCUvgWUIf2vhk5eUnSkJELy7JtJfv1qOGM_UZtxu0FI3BkpUQMxdX-aO3xdvfTKteAkbAc2vXy1xCXu"
    }
    ```

**Comment by xtrinch** [comment]
Nothing, this is legacy and leftover from the old fcm v1 API
