### ISSUE TITLE
Doesn't work on Firefox nor Safari neither

### ISSUE THREAD

**Issue by dkdndes** [xtrinch/fcm-django-web-demo#6]
I use Python3, and start the web server this way:

     $  python3 -m http.server 8001

and as a result see this (both browsers (firefox and safari)):

<img width="1025" alt="bildschirmfoto 2018-12-09 um 19 04 45" src="https://user-images.githubusercontent.com/1189088/49700923-814a1a80-fbe5-11e8-8c81-e081a7bb4343.png">

If I open the application within Django after I did the following additional steps (not documented, but the default steps for Django):

    $ python manage.py migrate
    $ python createsuperuser
    $ python manage.py runserver

the following page is shown:

<img width="998" alt="bildschirmfoto 2018-12-09 um 19 08 09" src="https://user-images.githubusercontent.com/1189088/49700938-cd955a80-fbe5-11e8-8739-616a16da3c9f.png">

and in the sub-screen I see the following:

<img width="983" alt="bildschirmfoto 2018-12-09 um 19 08 46" src="https://user-images.githubusercontent.com/1189088/49700948-e0a82a80-fbe5-11e8-9dcc-9d6301d2b8b0.png">

I have to admit that it is not self-explanatory, and I would appreciate if you explain it or let me know where the error is.

I like to add that the key to my app was added, and the key you provided within your source code was not used.

I like to understand where the steps happen which registers the web browser as a device and lets Django receive a DEVICE ID TOKEN which is then saved in the DB, which enables a developer at a later stage to send (if bulk is not used) to the individual device of the user a message.
 
The documentation was (for me) not clear enough about it, and I am not sure now if your lib provides this or not?

**Comment by xtrinch** [comment]
Have you tried with the default setup? Perhaps you have a problem with your key.

**Comment by dkdndes** [comment]
I used your default setup, and it works. I see now a token for the device, and its possible to enter it within the django-fcm admin server app. I am also able to use the admin pulldown and can send messages. Shall I update your docu, it could help to provide some screenshots?

**Comment by xtrinch** [comment]
Yes it would be great if you could update the documentation. Thanks in advance
